// <auto-generated />
using Bookstore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bookstore.Migrations
{
    [DbContext(typeof(BookstoreDBContext))]
    [Migration("20241005170522_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bookstore.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Aldous Huxley",
                            Genre = "Dystopian",
                            Price = 9.99m,
                            Title = "Brave New World"
                        },
                        new
                        {
                            Id = 2,
                            Author = "J.D. Salinger",
                            Genre = "Fiction",
                            Price = 8.49m,
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Jane Austen",
                            Genre = "Romance",
                            Price = 6.99m,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Herman Melville",
                            Genre = "Adventure",
                            Price = 11.50m,
                            Title = "Moby Dick"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Paulo Coelho",
                            Genre = "Philosophical",
                            Price = 9.49m,
                            Title = "The Alchemist"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Leo Tolstoy",
                            Genre = "Historical Fiction",
                            Price = 12.99m,
                            Title = "War and Peace"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Ray Bradbury",
                            Genre = "Dystopian",
                            Price = 7.49m,
                            Title = "Fahrenheit 451"
                        },
                        new
                        {
                            Id = 8,
                            Author = "J.R.R. Tolkien",
                            Genre = "Fantasy",
                            Price = 8.99m,
                            Title = "The Hobbit"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
